# Generated by Django 5.0.6 on 2024-06-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Price', models.CharField(max_length=100)),
                ('Image', models.ImageField(upload_to='ProductImage/')),
                ('Description', models.CharField(max_length=1000)),
                ('Category', models.CharField(max_length=500)),
            ],
        ),
    ]
